name: advdebias
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - coloredlogs=10.0
  - gdown=3.9.0
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pillow=6.1
  - python=3.7.3
  - scikit-learn=0.22.1
  - scipy=1.3.0
  - seaborn=0.9.0
  - pytorch=1.2.0
  - torchvision=0.4.0
